CREATE TYPE horario_status AS ENUM ('livre', 'reservado', 'em_visitacao');

CREATE TABLE IF NOT EXISTS horario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comeco TIMESTAMP NOT NULL,
    fim TIMESTAMP NOT NULL,
    status horario_status DEFAULT 'livre' NOT NULL,
    EXCLUDE USING GIST (TSRANGE(comeco, fim) WITH &&)
);
